name:                quickcheck-patterns
version:             0.1.0.0
github:              "agustinmista/quickcheck-patterns"
license:             BSD3
license-file:        LICENSE
author:              "Agustín Mista"
maintainer:          "Agustín Mista"
copyright:           "2018 Agustín Mista"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            QuickCheck utilities to generate data following pattern matchings.
category:            Testing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Please see the README on GitHub at <https://github.com/agustinmista/quickcheck-patterns#readme>

dependencies:
- base >= 4.7 && < 5
- extra

library:
  source-dirs:
    - src
  exposed-modules:
    - Test.QuickCheck.Patterns.TH
    - Test.QuickCheck.Patterns.Rep
  dependencies:
    - template-haskell
    - th-desugar
    - haskell-src-exts
    - ghc-prim
    - extra
    - split
    - filepath
    - directory
    - QuickCheck
