name:                dragen-struct
version:             0.1.0.0
github:              "OctopiChalmers/dragen-struct"
license:             BSD3
license-file:        LICENSE
author:              "Agustín Mista"
maintainer:          "Agustín Mista"
copyright:           "2019 Agustín Mista"

extra-source-files:
  - README.md

# Metadata used when publishing your package
synopsis:            
  QuickCheck utilities to derive random generators using structural information.
category: 
  Testing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Please see the README on GitHub at <https://github.com/OctopiChalmers/dragen-struct#readme>

dependencies:
  - base >= 4.7 && < 5

default-extensions:
  - AllowAmbiguousTypes
  - DataKinds
  - DeriveFunctor
  - DeriveGeneric
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - MultiParamTypeClasses
  - PolyKinds
  - Rank2Types
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances

library:
  source-dirs:
    - src
  exposed-modules:
    - Dragen.Struct
  dependencies:
    - template-haskell
    - th-desugar
    - haskell-src-exts
    - ghc-prim
    - containers
    - extra
    - split
    - filepath
    - directory
    - QuickCheck
    - reflection
    - matrix
    - vector
