name:                quickcheck-hrep
version:             0.1.0.0
github:              "agustinmista/quickcheck-hrep"
license:             BSD3
license-file:        LICENSE
author:              "Agustín Mista"
maintainer:          "Agustín Mista"
copyright:           "2018 Agustín Mista"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            QuickCheck utilities to generated constrained data based on higher-order representations.
category:            Testing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Please see the README on GitHub at <https://github.com/agustinmista/quickcheck-hrep#readme>

dependencies:
- base >= 4.7 && < 5
- extra

library:
  source-dirs:
    - src
    - test
  exposed-modules:
    - Test.QuickCheck.HRep
    - Test.QuickCheck.HRep.Infix
    - Test.QuickCheck.HRep.TH
    - Test.QuickCheck.HRep.TH.TypeRep
    - Test.QuickCheck.HRep.TH.FunPatsRep
    - Test.QuickCheck.HRep.TH.ModIntRep
    - Test.QuickCheck.Branching
    - GHC.Generics.Countable
    - Language.Haskell.TH.Desugar.Utils
  dependencies:
    - template-haskell
    - th-desugar
    - haskell-src-exts
    - ghc-prim
    - containers
    - extra
    - split
    - filepath
    - directory
    - QuickCheck
    - reflection
    - matrix
    - vector
