name:                dragen2
version:             0.1.0.0
github:              "OctopiChalmers/dragen2"
license:             BSD3
license-file:        LICENSE
author:              "Agustín Mista"
maintainer:          "Agustín Mista"
copyright:           "2019 Agustín Mista"

extra-source-files:
  - README.md

# Metadata used when publishing your package
synopsis:
  QuickCheck utilities to derive random generators using structural information.
category:
  Testing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Please see the README on GitHub at <https://github.com/OctopiChalmers/dragen2#readme>

dependencies:
  - base >= 4.7 && < 5
  - QuickCheck
  - vector
  - reflection

flags:
  debug:
    description: Turns on debug messages
    manual: True
    default: True

default-extensions:
  - AllowAmbiguousTypes
  - ConstraintKinds
  - DataKinds
  - DeriveFunctor
  - DeriveGeneric
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - MultiParamTypeClasses
  - NoStarIsType
  - PolyKinds
  - QuantifiedConstraints
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances

library:
  source-dirs:
    - src
  exposed-modules:
    - Test.Dragen2
  dependencies:
    - containers
    - directory
    - extra
    - filepath
    - ghc-prim
    - haskell-src-exts
    - matrix
    - split
    - ghc-boot-th
    - template-haskell
    - th-desugar
    - ansi-terminal
    - pretty
  when:
    - condition: flag(debug)
      cpp-options: -DDEBUG

tests:
  dragen2-tests:
    source-dirs:
      - test
    main: Main.hs
    dependencies:
      - dragen2
    cpp-options: -DDEBUG

benchmarks:
  dragen2-benchmarks:
    source-dirs:
      - bench
    main: Main.hs
    dependencies:
      - dragen2
      - criterion
      - deepseq
      - th-desugar
      - template-haskell
    ghc-options: -O2
    cpp-options: -DDEBUG
